name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BuildConfiguration: Release

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Install ZeroQL CLI
      run: |
        dotnet tool install --global ZeroQL.CLI
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Build
      shell: bash
      run: dotnet build --configuration $BuildConfiguration
